-- 169 unique exercises seeded
with seed (name, muscle, mtype) as (values
  ('Flat Barbell Bench Press', 'chest', 'weight_reps'),
  ('Incline Barbell Bench Press', 'chest', 'weight_reps'),
  ('Decline Barbell Bench Press', 'chest', 'weight_reps'),
  ('Close-Grip Barbell Bench Press', 'chest', 'weight_reps'),
  ('Barbell Pullover', 'chest', 'weight_reps'),
  ('Flat Dumbbell Bench Press', 'chest', 'weight_reps'),
  ('Incline Dumbbell Bench Press', 'chest', 'weight_reps'),
  ('Decline Dumbbell Bench Press', 'chest', 'weight_reps'),
  ('Close-Grip Dumbbell Press', 'chest', 'weight_reps'),
  ('Dumbbell Pullover', 'chest', 'weight_reps'),
  ('Dips', 'chest', 'bodyweight_reps'),
  ('Wide-Grip Lat Pulldown', 'back', 'weight_reps'),
  ('Close-Grip Lat Pulldown', 'back', 'weight_reps'),
  ('Reverse-Grip Lat Pulldown', 'back', 'weight_reps'),
  ('Single-Arm Lat Pulldown', 'back', 'weight_reps'),
  ('Straight-Arm Pulldown', 'back', 'weight_reps'),
  ('Seated Cable Row (Wide Grip)', 'back', 'weight_reps'),
  ('Seated Cable Row (Close Grip)', 'back', 'weight_reps'),
  ('Single-Arm Cable Row', 'back', 'weight_reps'),
  ('Cable Face Pull', 'back', 'weight_reps'),
  ('High Cable Row', 'back', 'weight_reps'),
  ('Pull-Up', 'back', 'bodyweight_reps'),
  ('Overhead Barbell Press', 'shoulders', 'weight_reps'),
  ('Seated Barbell Shoulder Press', 'shoulders', 'weight_reps'),
  ('Barbell Push Press', 'shoulders', 'weight_reps'),
  ('Behind-the-Neck Press', 'shoulders', 'weight_reps'),
  ('Barbell Upright Row', 'shoulders', 'weight_reps'),
  ('Landmine Press', 'shoulders', 'weight_reps'),
  ('Seated Dumbbell Shoulder Press', 'shoulders', 'weight_reps'),
  ('Standing Dumbbell Shoulder Press', 'shoulders', 'weight_reps'),
  ('Arnold Press', 'shoulders', 'weight_reps'),
  ('Dumbbell Lateral Raise', 'shoulders', 'weight_reps'),
  ('Dumbbell Front Raise', 'shoulders', 'weight_reps'),
  ('Dumbbell Rear Delt Fly', 'shoulders', 'weight_reps'),
  ('Dumbbell Upright Row', 'shoulders', 'weight_reps'),
  ('Dumbbell Shrug', 'shoulders', 'weight_reps'),
  ('Cable Lateral Raise', 'shoulders', 'weight_reps'),
  ('Cable Front Raise', 'shoulders', 'weight_reps'),
  ('Cable Reverse Fly', 'shoulders', 'weight_reps'),
  ('Cable Face Pull (Shoulders)', 'shoulders', 'weight_reps'),
  ('Cable Upright Row', 'shoulders', 'weight_reps'),
  ('Machine Shoulder Press', 'shoulders', 'weight_reps'),
  ('Machine Lateral Raise', 'shoulders', 'weight_reps'),
  ('Reverse Pec Deck (Rear Delts)', 'shoulders', 'weight_reps'),
  ('Smith Machine Shoulder Press', 'shoulders', 'weight_reps'),
  ('Pike Push-Up', 'shoulders', 'bodyweight_reps'),
  ('Handstand Push-Up', 'shoulders', 'bodyweight_reps'),
  ('Wall Walk', 'shoulders', 'bodyweight_reps'),
  ('Close-Grip Bench Press', 'triceps', 'weight_reps'),
  ('Barbell Skull Crusher', 'triceps', 'weight_reps'),
  ('Barbell Overhead Tricep Extension', 'triceps', 'weight_reps'),
  ('Tricep Pushdown (Straight Bar)', 'triceps', 'weight_reps'),
  ('Tricep Pushdown (Rope)', 'triceps', 'weight_reps'),
  ('Reverse-Grip Pushdown', 'triceps', 'weight_reps'),
  ('Overhead Cable Tricep Extension', 'triceps', 'weight_reps'),
  ('Single-Arm Cable Pushdown', 'triceps', 'weight_reps'),
  ('Dumbbell Skull Crusher', 'triceps', 'weight_reps'),
  ('Overhead Dumbbell Tricep Extension', 'triceps', 'weight_reps'),
  ('Dumbbell Kickback', 'triceps', 'weight_reps'),
  ('Single-Arm Overhead Extension', 'triceps', 'weight_reps'),
  ('Barbell Curl', 'biceps', 'weight_reps'),
  ('EZ Bar Curl', 'biceps', 'weight_reps'),
  ('Reverse-Grip Barbell Curl', 'biceps', 'weight_reps'),
  ('Drag Curl', 'biceps', 'weight_reps'),
  ('Dumbbell Bicep Curl', 'biceps', 'weight_reps'),
  ('Hammer Curl', 'biceps', 'weight_reps'),
  ('Incline Dumbbell Curl', 'biceps', 'weight_reps'),
  ('Concentration Curl', 'biceps', 'weight_reps'),
  ('Zottman Curl', 'biceps', 'weight_reps'),
  ('Cable Curl (Straight Bar)', 'biceps', 'weight_reps'),
  ('Cable Curl (Rope)', 'biceps', 'weight_reps'),
  ('Reverse-Grip Cable Curl', 'biceps', 'weight_reps'),
  ('Single-Arm Cable Curl', 'biceps', 'weight_reps'),
  ('High Cable Curl', 'biceps', 'weight_reps'),
  ('Chin-Up', 'biceps', 'bodyweight_reps'),
  ('Inverted Row', 'biceps', 'bodyweight_reps'),
  ('Wrist Curl', 'forearms', 'weight_reps'),
  ('Reverse Wrist Curl', 'forearms', 'weight_reps'),
  ('Behind-the-Back Barbell Wrist Curl', 'forearms', 'weight_reps'),
  ('Single-Arm Dumbbell Wrist Curl', 'forearms', 'weight_reps'),
  ('Farmer''s Carry', 'forearms', 'weight_reps'),
  ('Cable Wrist Curl', 'forearms', 'weight_reps'),
  ('Dead Hang', 'forearms', 'timed'),
  ('Towel Pull-Up', 'forearms', 'bodyweight_reps'),
  ('Plate Pinch', 'forearms', 'timed'),
  ('Hand Gripper', 'forearms', 'reps_only'),
  ('Rice Bucket', 'forearms', 'timed'),
  ('Back Squat', 'legs', 'weight_reps'),
  ('Front Squat', 'legs', 'weight_reps'),
  ('Romanian Deadlift', 'legs', 'weight_reps'),
  ('Conventional Deadlift', 'legs', 'weight_reps'),
  ('Sumo Deadlift', 'legs', 'weight_reps'),
  ('Good Morning', 'legs', 'weight_reps'),
  ('Dumbbell Squat', 'legs', 'weight_reps'),
  ('Dumbbell Romanian Deadlift', 'legs', 'weight_reps'),
  ('Dumbbell Lunge', 'legs', 'weight_reps'),
  ('Dumbbell Step-Up', 'legs', 'weight_reps'),
  ('Dumbbell Sumo Squat', 'legs', 'weight_reps'),
  ('Dumbbell Bulgarian Split Squat', 'legs', 'weight_reps'),
  ('Leg Press', 'legs', 'weight_reps'),
  ('Leg Extension', 'legs', 'weight_reps'),
  ('Leg Curl', 'legs', 'weight_reps'),
  ('Seated Leg Curl', 'legs', 'weight_reps'),
  ('Hip Abduction Machine', 'legs', 'weight_reps'),
  ('Hip Adduction Machine', 'legs', 'weight_reps'),
  ('Smith Machine Squat', 'legs', 'weight_reps'),
  ('Hack Squat Machine', 'legs', 'weight_reps'),
  ('Cable Crunch', 'core', 'weight_reps'),
  ('Pallof Press', 'core', 'weight_reps'),
  ('Cable Woodchop', 'core', 'weight_reps'),
  ('High-to-Low Cable Chop', 'core', 'weight_reps'),
  ('Landmine Rotation', 'core', 'weight_reps'),
  ('Decline Weighted Crunch', 'core', 'weight_reps'),
  ('Weighted Sit-Up', 'core', 'weight_reps'),
  ('Dumbbell Side Bend', 'core', 'weight_reps'),
  ('Ab Wheel Rollout', 'core', 'reps_only'),
  ('Crunch', 'core', 'bodyweight_reps'),
  ('Sit-Up', 'core', 'bodyweight_reps'),
  ('Reverse Crunch', 'core', 'bodyweight_reps'),
  ('Leg Raise', 'core', 'bodyweight_reps'),
  ('Hanging Knee Raise', 'core', 'bodyweight_reps'),
  ('Bicycle Crunch', 'core', 'bodyweight_reps'),
  ('V-Up', 'core', 'bodyweight_reps'),
  ('Hanging Leg Raise', 'core', 'bodyweight_reps'),
  ('Dragon Flag', 'core', 'bodyweight_reps'),
  ('Lying Leg Raise', 'core', 'bodyweight_reps'),
  ('Russian Twist', 'core', 'bodyweight_reps'),
  ('Bird Dog', 'core', 'bodyweight_reps'),
  ('Plank', 'core', 'timed'),
  ('Side Plank', 'core', 'timed'),
  ('Hollow Body Hold', 'core', 'timed'),
  ('Dead Bug', 'core', 'timed'),
  ('RKC Plank', 'core', 'timed'),
  ('Side Plank with Rotation', 'core', 'timed'),
  ('Copenhagen Plank', 'core', 'timed'),
  ('Push-Up', 'bodyweight', 'bodyweight_reps'),
  ('Wide-Grip Push-Up', 'bodyweight', 'bodyweight_reps'),
  ('Diamond Push-Up', 'bodyweight', 'bodyweight_reps'),
  ('Decline Push-Up', 'bodyweight', 'bodyweight_reps'),
  ('Archer Push-Up', 'bodyweight', 'bodyweight_reps'),
  ('Close-Grip Push-Up', 'bodyweight', 'bodyweight_reps'),
  ('Neutral-Grip Pull-Up', 'bodyweight', 'bodyweight_reps'),
  ('Scapular Pull-Up', 'bodyweight', 'bodyweight_reps'),
  ('Face Pull (Band)', 'bodyweight', 'bodyweight_reps'),
  ('Inverted Row (Bodyweight)', 'bodyweight', 'bodyweight_reps'),
  ('Bodyweight Squat', 'bodyweight', 'bodyweight_reps'),
  ('Bulgarian Split Squat', 'bodyweight', 'bodyweight_reps'),
  ('Reverse Lunge', 'bodyweight', 'bodyweight_reps'),
  ('Walking Lunge', 'bodyweight', 'bodyweight_reps'),
  ('Pistol Squat', 'bodyweight', 'bodyweight_reps'),
  ('Glute Bridge', 'bodyweight', 'bodyweight_reps'),
  ('Hip Thrust (Single Leg)', 'bodyweight', 'bodyweight_reps'),
  ('Nordic Hamstring Curl', 'bodyweight', 'bodyweight_reps'),
  ('Wall Sit', 'bodyweight', 'timed'),
  ('Jump Squat', 'bodyweight', 'reps_only'),
  ('Burpee', 'bodyweight', 'reps_only'),
  ('Mountain Climber', 'bodyweight', 'reps_only'),
  ('Jumping Jack', 'bodyweight', 'reps_only'),
  ('Box Jump', 'bodyweight', 'reps_only'),
  ('Broad Jump', 'bodyweight', 'reps_only'),
  ('Handstand Hold', 'bodyweight', 'timed'),
  ('Bear Crawl', 'bodyweight', 'timed'),
  ('Treadmill', 'cardio', 'cardio'),
  ('Incline Treadmill Walk', 'cardio', 'cardio'),
  ('Stationary Bike', 'cardio', 'cardio'),
  ('Rowing Machine', 'cardio', 'cardio'),
  ('Elliptical', 'cardio', 'cardio'),
  ('Stair Climber', 'cardio', 'cardio'),
  ('Ski Erg', 'cardio', 'cardio')
)
insert into public.exercises (name, muscle_group, measurement_type, is_custom, created_by_user_id)
select s.name, s.muscle, s.mtype, false, null
from seed s
where not exists (select 1 from public.exercises e where lower(e.name) = lower(s.name));
select count(*) as exercises_now from public.exercises;
